package com.whitaker.models;

public enum PasswordErrorType {
	
	NULL_PASSWORD_ERROR,
	NULL_PATTERN_ERROR,
	NULL_DUP_CHECKER_ERROR,
	LENGTH_VALIDATION_ERROR,
	CHARACTER_VALIDATION_ERROR,
	NUMERIC_VALIDATION_ERROR,
	CHARACTER_SEQUENCE_VALIDATION_ERROR,
	DUPLICATE_VALIDATION_ERROR

}